### PR TITLE
[WIP]: implement a better hashing function

### PR DESCRIPTION
**Pull request by mattyclarkson**
This does a better job of hashing the nodes. It takes into account the end of the text, the start/end timestamps and more of the enumerations text. The unit test now discards false positives (where generated test nodes are identical) and runs tests until a timeout (20secs on CI/5secs locally).

Need to check the performance is still fast enough on the shitty devices.

### CODE REVIEW

**Comment by mattyclarkson** [comment]
@grey this doesn't work at all. I need to do proper math to figure out how to fold the common patterns into the necessary 53bits available. I suggest that we just remove the hashing from `react-native-dom` for now. It means that if anyone changes the nested nodes they won't be re-rendered, but we never do that so will save time whilst we put this on the back burner.

**Comment by ionTea** [comment]
Why do we use our own hash function? Why not use some off-the-shelf hash funciton like sha or md5?

**Comment by ionTea** [comment]
echo _echo_ _echo_ _echo_ 💀

**Comment by ionTea** [comment]
*echo* _echo_ _echo_ _echo_ 💀

**Pull request closed without merging**
